---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dregissi/catering-backend
    - cd pdidi-backend
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt